// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: playground.proto

package playground

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Process struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                   int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_ParentId             int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId"`
	xxx_hidden_Pid                  int64                  `protobuf:"varint,3,opt,name=pid"`
	xxx_hidden_StartTime            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime"`
	xxx_hidden_EndTime              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime"`
	xxx_hidden_WorkingDirectory     *string                `protobuf:"bytes,6,opt,name=working_directory,json=workingDirectory"`
	xxx_hidden_Args                 []string               `protobuf:"bytes,7,rep,name=args"`
	xxx_hidden_FileReadIds          []int64                `protobuf:"varint,8,rep,packed,name=file_read_ids,json=fileReadIds"`
	xxx_hidden_FileWriteIds         []int64                `protobuf:"varint,9,rep,packed,name=file_write_ids,json=fileWriteIds"`
	xxx_hidden_PipeReadFromActionId int64                  `protobuf:"varint,10,opt,name=pipe_read_from_action_id,json=pipeReadFromActionId"`
	xxx_hidden_ExitSignal           *string                `protobuf:"bytes,11,opt,name=exit_signal,json=exitSignal"`
	xxx_hidden_ExitStatus           uint32                 `protobuf:"varint,12,opt,name=exit_status,json=exitStatus"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_playground_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Process) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Process) GetParentId() int64 {
	if x != nil {
		return x.xxx_hidden_ParentId
	}
	return 0
}

func (x *Process) GetPid() int64 {
	if x != nil {
		return x.xxx_hidden_Pid
	}
	return 0
}

func (x *Process) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTime
	}
	return nil
}

func (x *Process) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndTime
	}
	return nil
}

func (x *Process) GetWorkingDirectory() string {
	if x != nil {
		if x.xxx_hidden_WorkingDirectory != nil {
			return *x.xxx_hidden_WorkingDirectory
		}
		return ""
	}
	return ""
}

func (x *Process) GetArgs() []string {
	if x != nil {
		return x.xxx_hidden_Args
	}
	return nil
}

func (x *Process) GetFileReadIds() []int64 {
	if x != nil {
		return x.xxx_hidden_FileReadIds
	}
	return nil
}

func (x *Process) GetFileWriteIds() []int64 {
	if x != nil {
		return x.xxx_hidden_FileWriteIds
	}
	return nil
}

func (x *Process) GetPipeReadFromActionId() int64 {
	if x != nil {
		return x.xxx_hidden_PipeReadFromActionId
	}
	return 0
}

func (x *Process) GetExitSignal() string {
	if x != nil {
		if x.xxx_hidden_ExitSignal != nil {
			return *x.xxx_hidden_ExitSignal
		}
		return ""
	}
	return ""
}

func (x *Process) GetExitStatus() uint32 {
	if x != nil {
		return x.xxx_hidden_ExitStatus
	}
	return 0
}

func (x *Process) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *Process) SetParentId(v int64) {
	x.xxx_hidden_ParentId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *Process) SetPid(v int64) {
	x.xxx_hidden_Pid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *Process) SetStartTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTime = v
}

func (x *Process) SetEndTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndTime = v
}

func (x *Process) SetWorkingDirectory(v string) {
	x.xxx_hidden_WorkingDirectory = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *Process) SetArgs(v []string) {
	x.xxx_hidden_Args = v
}

func (x *Process) SetFileReadIds(v []int64) {
	x.xxx_hidden_FileReadIds = v
}

func (x *Process) SetFileWriteIds(v []int64) {
	x.xxx_hidden_FileWriteIds = v
}

func (x *Process) SetPipeReadFromActionId(v int64) {
	x.xxx_hidden_PipeReadFromActionId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *Process) SetExitSignal(v string) {
	x.xxx_hidden_ExitSignal = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *Process) SetExitStatus(v uint32) {
	x.xxx_hidden_ExitStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *Process) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Process) HasParentId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Process) HasPid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Process) HasStartTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTime != nil
}

func (x *Process) HasEndTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndTime != nil
}

func (x *Process) HasWorkingDirectory() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Process) HasPipeReadFromActionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *Process) HasExitSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *Process) HasExitStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *Process) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Process) ClearParentId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ParentId = 0
}

func (x *Process) ClearPid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Pid = 0
}

func (x *Process) ClearStartTime() {
	x.xxx_hidden_StartTime = nil
}

func (x *Process) ClearEndTime() {
	x.xxx_hidden_EndTime = nil
}

func (x *Process) ClearWorkingDirectory() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_WorkingDirectory = nil
}

func (x *Process) ClearPipeReadFromActionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_PipeReadFromActionId = 0
}

func (x *Process) ClearExitSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_ExitSignal = nil
}

func (x *Process) ClearExitStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_ExitStatus = 0
}

type Process_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                   *int64
	ParentId             *int64
	Pid                  *int64
	StartTime            *timestamppb.Timestamp
	EndTime              *timestamppb.Timestamp
	WorkingDirectory     *string
	Args                 []string
	FileReadIds          []int64
	FileWriteIds         []int64
	PipeReadFromActionId *int64
	ExitSignal           *string
	ExitStatus           *uint32
}

func (b0 Process_builder) Build() *Process {
	m0 := &Process{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_Id = *b.Id
	}
	if b.ParentId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_ParentId = *b.ParentId
	}
	if b.Pid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_Pid = *b.Pid
	}
	x.xxx_hidden_StartTime = b.StartTime
	x.xxx_hidden_EndTime = b.EndTime
	if b.WorkingDirectory != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_WorkingDirectory = b.WorkingDirectory
	}
	x.xxx_hidden_Args = b.Args
	x.xxx_hidden_FileReadIds = b.FileReadIds
	x.xxx_hidden_FileWriteIds = b.FileWriteIds
	if b.PipeReadFromActionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_PipeReadFromActionId = *b.PipeReadFromActionId
	}
	if b.ExitSignal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_ExitSignal = b.ExitSignal
	}
	if b.ExitStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_ExitStatus = *b.ExitStatus
	}
	return m0
}

type SysGraph struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Processes     *[]*Process            `protobuf:"bytes,1,rep,name=processes"`
	xxx_hidden_Files         []string               `protobuf:"bytes,2,rep,name=files"`
	xxx_hidden_Analysis      *Analysis              `protobuf:"bytes,3,opt,name=analysis"`
	xxx_hidden_AnalysisError *string                `protobuf:"bytes,4,opt,name=analysis_error,json=analysisError"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SysGraph) Reset() {
	*x = SysGraph{}
	mi := &file_playground_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysGraph) ProtoMessage() {}

func (x *SysGraph) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SysGraph) GetProcesses() []*Process {
	if x != nil {
		if x.xxx_hidden_Processes != nil {
			return *x.xxx_hidden_Processes
		}
	}
	return nil
}

func (x *SysGraph) GetFiles() []string {
	if x != nil {
		return x.xxx_hidden_Files
	}
	return nil
}

func (x *SysGraph) GetAnalysis() *Analysis {
	if x != nil {
		return x.xxx_hidden_Analysis
	}
	return nil
}

func (x *SysGraph) GetAnalysisError() string {
	if x != nil {
		if x.xxx_hidden_AnalysisError != nil {
			return *x.xxx_hidden_AnalysisError
		}
		return ""
	}
	return ""
}

func (x *SysGraph) SetProcesses(v []*Process) {
	x.xxx_hidden_Processes = &v
}

func (x *SysGraph) SetFiles(v []string) {
	x.xxx_hidden_Files = v
}

func (x *SysGraph) SetAnalysis(v *Analysis) {
	x.xxx_hidden_Analysis = v
}

func (x *SysGraph) SetAnalysisError(v string) {
	x.xxx_hidden_AnalysisError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *SysGraph) HasAnalysis() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Analysis != nil
}

func (x *SysGraph) HasAnalysisError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SysGraph) ClearAnalysis() {
	x.xxx_hidden_Analysis = nil
}

func (x *SysGraph) ClearAnalysisError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AnalysisError = nil
}

type SysGraph_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Processes     []*Process
	Files         []string
	Analysis      *Analysis
	AnalysisError *string
}

func (b0 SysGraph_builder) Build() *SysGraph {
	m0 := &SysGraph{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Processes = &b.Processes
	x.xxx_hidden_Files = b.Files
	x.xxx_hidden_Analysis = b.Analysis
	if b.AnalysisError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_AnalysisError = b.AnalysisError
	}
	return m0
}

// Analysis represents the analysis results for a sysgraph.
type Analysis struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Rules *[]*Rule               `protobuf:"bytes,1,rep,name=rules"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_playground_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Analysis) GetRules() []*Rule {
	if x != nil {
		if x.xxx_hidden_Rules != nil {
			return *x.xxx_hidden_Rules
		}
	}
	return nil
}

func (x *Analysis) SetRules(v []*Rule) {
	x.xxx_hidden_Rules = &v
}

type Analysis_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Rules []*Rule
}

func (b0 Analysis_builder) Build() *Analysis {
	m0 := &Analysis{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Rules = &b.Rules
	return m0
}

// Rule represents an invariant rule for a sysgraph.
type Rule struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RuleName    *string                `protobuf:"bytes,1,opt,name=rule_name,json=ruleName"`
	xxx_hidden_Description *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Matches     *[]*RuleMatch          `protobuf:"bytes,3,rep,name=matches"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_playground_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Rule) GetRuleName() string {
	if x != nil {
		if x.xxx_hidden_RuleName != nil {
			return *x.xxx_hidden_RuleName
		}
		return ""
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *Rule) GetMatches() []*RuleMatch {
	if x != nil {
		if x.xxx_hidden_Matches != nil {
			return *x.xxx_hidden_Matches
		}
	}
	return nil
}

func (x *Rule) SetRuleName(v string) {
	x.xxx_hidden_RuleName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Rule) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Rule) SetMatches(v []*RuleMatch) {
	x.xxx_hidden_Matches = &v
}

func (x *Rule) HasRuleName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Rule) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Rule) ClearRuleName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RuleName = nil
}

func (x *Rule) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

type Rule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RuleName    *string
	Description *string
	Matches     []*RuleMatch
}

func (b0 Rule_builder) Build() *Rule {
	m0 := &Rule{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RuleName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_RuleName = b.RuleName
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_Matches = &b.Matches
	return m0
}

// RuleMatch represents the nodes in a sysgraph relevant to a rule violation.
type RuleMatch struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ProcessIds  []int64                `protobuf:"varint,1,rep,packed,name=process_ids,json=processIds"`
	xxx_hidden_ResourceIds []int64                `protobuf:"varint,2,rep,packed,name=resource_ids,json=resourceIds"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RuleMatch) Reset() {
	*x = RuleMatch{}
	mi := &file_playground_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleMatch) ProtoMessage() {}

func (x *RuleMatch) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RuleMatch) GetProcessIds() []int64 {
	if x != nil {
		return x.xxx_hidden_ProcessIds
	}
	return nil
}

func (x *RuleMatch) GetResourceIds() []int64 {
	if x != nil {
		return x.xxx_hidden_ResourceIds
	}
	return nil
}

func (x *RuleMatch) SetProcessIds(v []int64) {
	x.xxx_hidden_ProcessIds = v
}

func (x *RuleMatch) SetResourceIds(v []int64) {
	x.xxx_hidden_ResourceIds = v
}

type RuleMatch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ProcessIds  []int64
	ResourceIds []int64
}

func (b0 RuleMatch_builder) Build() *RuleMatch {
	m0 := &RuleMatch{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ProcessIds = b.ProcessIds
	x.xxx_hidden_ResourceIds = b.ResourceIds
	return m0
}

type SysGraphResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Graph *SysGraph              `protobuf:"bytes,1,opt,name=graph"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SysGraphResponse) Reset() {
	*x = SysGraphResponse{}
	mi := &file_playground_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysGraphResponse) ProtoMessage() {}

func (x *SysGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playground_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SysGraphResponse) GetGraph() *SysGraph {
	if x != nil {
		return x.xxx_hidden_Graph
	}
	return nil
}

func (x *SysGraphResponse) SetGraph(v *SysGraph) {
	x.xxx_hidden_Graph = v
}

func (x *SysGraphResponse) HasGraph() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Graph != nil
}

func (x *SysGraphResponse) ClearGraph() {
	x.xxx_hidden_Graph = nil
}

type SysGraphResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Graph *SysGraph
}

func (b0 SysGraphResponse_builder) Build() *SysGraphResponse {
	m0 := &SysGraphResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Graph = b.Graph
	return m0
}

var File_playground_proto protoreflect.FileDescriptor

const file_playground_proto_rawDesc = "" +
	"\n" +
	"\x10playground.proto\x127devtools.foundry.x.sysgraph.playground.proto.playground\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x03\n" +
	"\aProcess\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12+\n" +
	"\x11working_directory\x18\x06 \x01(\tR\x10workingDirectory\x12\x12\n" +
	"\x04args\x18\a \x03(\tR\x04args\x12\"\n" +
	"\rfile_read_ids\x18\b \x03(\x03R\vfileReadIds\x12$\n" +
	"\x0efile_write_ids\x18\t \x03(\x03R\ffileWriteIds\x126\n" +
	"\x18pipe_read_from_action_id\x18\n" +
	" \x01(\x03R\x14pipeReadFromActionId\x12\x1f\n" +
	"\vexit_signal\x18\v \x01(\tR\n" +
	"exitSignal\x12\x1f\n" +
	"\vexit_status\x18\f \x01(\rR\n" +
	"exitStatus\"\x86\x02\n" +
	"\bSysGraph\x12^\n" +
	"\tprocesses\x18\x01 \x03(\v2@.devtools.foundry.x.sysgraph.playground.proto.playground.ProcessR\tprocesses\x12\x14\n" +
	"\x05files\x18\x02 \x03(\tR\x05files\x12]\n" +
	"\banalysis\x18\x03 \x01(\v2A.devtools.foundry.x.sysgraph.playground.proto.playground.AnalysisR\banalysis\x12%\n" +
	"\x0eanalysis_error\x18\x04 \x01(\tR\ranalysisError\"_\n" +
	"\bAnalysis\x12S\n" +
	"\x05rules\x18\x01 \x03(\v2=.devtools.foundry.x.sysgraph.playground.proto.playground.RuleR\x05rules\"\xa3\x01\n" +
	"\x04Rule\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\\\n" +
	"\amatches\x18\x03 \x03(\v2B.devtools.foundry.x.sysgraph.playground.proto.playground.RuleMatchR\amatches\"O\n" +
	"\tRuleMatch\x12\x1f\n" +
	"\vprocess_ids\x18\x01 \x03(\x03R\n" +
	"processIds\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\x03R\vresourceIds\"k\n" +
	"\x10SysGraphResponse\x12W\n" +
	"\x05graph\x18\x01 \x01(\v2A.devtools.foundry.x.sysgraph.playground.proto.playground.SysGraphR\x05graphB-Z+github.com/google/sysgraph/proto/playgroundb\beditionsp\xe9\a"

var file_playground_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_playground_proto_goTypes = []any{
	(*Process)(nil),               // 0: devtools.foundry.x.sysgraph.playground.proto.playground.Process
	(*SysGraph)(nil),              // 1: devtools.foundry.x.sysgraph.playground.proto.playground.SysGraph
	(*Analysis)(nil),              // 2: devtools.foundry.x.sysgraph.playground.proto.playground.Analysis
	(*Rule)(nil),                  // 3: devtools.foundry.x.sysgraph.playground.proto.playground.Rule
	(*RuleMatch)(nil),             // 4: devtools.foundry.x.sysgraph.playground.proto.playground.RuleMatch
	(*SysGraphResponse)(nil),      // 5: devtools.foundry.x.sysgraph.playground.proto.playground.SysGraphResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_playground_proto_depIdxs = []int32{
	6, // 0: devtools.foundry.x.sysgraph.playground.proto.playground.Process.start_time:type_name -> google.protobuf.Timestamp
	6, // 1: devtools.foundry.x.sysgraph.playground.proto.playground.Process.end_time:type_name -> google.protobuf.Timestamp
	0, // 2: devtools.foundry.x.sysgraph.playground.proto.playground.SysGraph.processes:type_name -> devtools.foundry.x.sysgraph.playground.proto.playground.Process
	2, // 3: devtools.foundry.x.sysgraph.playground.proto.playground.SysGraph.analysis:type_name -> devtools.foundry.x.sysgraph.playground.proto.playground.Analysis
	3, // 4: devtools.foundry.x.sysgraph.playground.proto.playground.Analysis.rules:type_name -> devtools.foundry.x.sysgraph.playground.proto.playground.Rule
	4, // 5: devtools.foundry.x.sysgraph.playground.proto.playground.Rule.matches:type_name -> devtools.foundry.x.sysgraph.playground.proto.playground.RuleMatch
	1, // 6: devtools.foundry.x.sysgraph.playground.proto.playground.SysGraphResponse.graph:type_name -> devtools.foundry.x.sysgraph.playground.proto.playground.SysGraph
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_playground_proto_init() }
func file_playground_proto_init() {
	if File_playground_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playground_proto_rawDesc), len(file_playground_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playground_proto_goTypes,
		DependencyIndexes: file_playground_proto_depIdxs,
		MessageInfos:      file_playground_proto_msgTypes,
	}.Build()
	File_playground_proto = out.File
	file_playground_proto_goTypes = nil
	file_playground_proto_depIdxs = nil
}
